// ⚙️ DONNÉES DU JEU — config de secours (la version en ligne est dans Firebase, éditable via admin.html)
const CONFIG_PAR_DEFAUT = {
  "persos": [
    {
      "image": "",
      "imageCarte": "",
      "munitions": 3,
      "recharge": 55,
      "modeleEchelle": 1,
      "modeleRotation": 0,
      "animRepos": "",
      "animMarche": "",
      "animAttaque": "",
      "nom": "ROKH",
      "element": "terre",
      "couleur": "#b7791f",
      "arme": "rocher",
      "pvMax": 8500,
      "vitesse": 3,
      "degats": 2000,
      "portee": 300,
      "delaiTir": 55,
      "modele": "modeles/rokh.glb"
    },
    {
      "image": "",
      "imageCarte": "",
      "munitions": 3,
      "recharge": 55,
      "modeleEchelle": 1.2,
      "modeleRotation": 0,
      "animRepos": "",
      "animMarche": "",
      "animAttaque": "",
      "nom": "ZEPHYR",
      "element": "air",
      "couleur": "#7dd3fc",
      "arme": "vent",
      "pvMax": 3800,
      "vitesse": 4.6,
      "degats": 950,
      "portee": 520,
      "delaiTir": 20,
      "modele": "modeles/zephyr.glb"
    },
    {
      "image": "",
      "imageCarte": "",
      "munitions": 3,
      "recharge": 55,
      "modeleEchelle": 1,
      "modeleRotation": 0,
      "animRepos": "",
      "animMarche": "",
      "animAttaque": "",
      "nom": "NAIA",
      "element": "eau",
      "couleur": "#3b82f6",
      "arme": "trident",
      "pvMax": 5400,
      "vitesse": 4,
      "degats": 1250,
      "portee": 400,
      "delaiTir": 28,
      "modele": "modeles/naia.glb"
    },
    {
      "image": "",
      "imageCarte": "",
      "munitions": 3,
      "recharge": 55,
      "modeleEchelle": 1,
      "modeleRotation": 0,
      "animRepos": "",
      "animMarche": "",
      "animAttaque": "",
      "nom": "PYRO",
      "element": "feu",
      "couleur": "#f97316",
      "arme": "boulefeu",
      "pvMax": 5000,
      "vitesse": 4.1,
      "degats": 1600,
      "portee": 360,
      "delaiTir": 34,
      "modele": "modeles/pyro.glb"
    },
    {
      "nom": "WIXY",
      "image": "images/wixy.png",
      "couleur": "#3498db",
      "pvMax": 6000,
      "vitesse": 3.4,
      "arme": "bombe",
      "degats": 2000,
      "portee": 300,
      "delaiTir": 45,
      "imageCarte": "",
      "munitions": 3,
      "recharge": 60,
      "element": "feu",
      "modele": "",
      "modeleEchelle": 1,
      "modeleRotation": 0,
      "animRepos": "",
      "animMarche": "",
      "animAttaque": ""
    },
    {
      "nom": "BORA",
      "image": "images/bora.png",
      "couleur": "#9b59b6",
      "pvMax": 4800,
      "vitesse": 4.3,
      "arme": "boomerang",
      "degats": 1250,
      "portee": 450,
      "delaiTir": 22,
      "imageCarte": "",
      "munitions": 3,
      "recharge": 45,
      "element": "terre",
      "modele": "",
      "modeleEchelle": 1,
      "modeleRotation": 0,
      "animRepos": "",
      "animMarche": "",
      "animAttaque": ""
    }
  ],
  "armes": {
    "bombe": {
      "nom": "Bombe",
      "image": "images/bombe.png",
      "type": "lob",
      "effet": "explosion",
      "vitesse": 9,
      "taille": 18,
      "rayon": 80,
      "couleur": "#ff9f1a",
      "forme": "zone",
      "nbCases": 3,
      "typeCase": "#",
      "dureeCase": 5,
      "delaiCase": 4
    },
    "boomerang": {
      "nom": "Boomerang",
      "image": "images/boomerang.png",
      "type": "retour",
      "effet": "entaille",
      "vitesse": 11,
      "taille": 18,
      "rayon": 0,
      "couleur": "#9cff57",
      "forme": "zone",
      "nbCases": 3,
      "typeCase": "#",
      "dureeCase": 5,
      "delaiCase": 4
    },
    "tir": {
      "nom": "Tir magique",
      "image": "",
      "type": "droit",
      "effet": "etincelle",
      "vitesse": 13,
      "taille": 10,
      "rayon": 0,
      "couleur": "#ffe14a",
      "forme": "zone",
      "nbCases": 3,
      "typeCase": "#",
      "dureeCase": 5,
      "delaiCase": 4
    },
    "seisme": {
      "nom": "Séisme",
      "image": "",
      "type": "terrain",
      "effet": "impact",
      "vitesse": 10,
      "taille": 16,
      "rayon": 0,
      "couleur": "#c98a4b",
      "forme": "mur",
      "nbCases": 3,
      "typeCase": "#",
      "dureeCase": 5,
      "delaiCase": 4
    },
    "ricochet": {
      "nom": "Laser ricochet",
      "image": "",
      "type": "droit",
      "effet": "etincelle",
      "vitesse": 14,
      "taille": 10,
      "rayon": 0,
      "couleur": "#5ad1ff",
      "rebonds": 3,
      "bonusRebond": 1.25,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350
    },
    "eclair": {
      "nom": "Éclair chercheur",
      "image": "",
      "type": "droit",
      "effet": "foudre",
      "vitesse": 13,
      "taille": 10,
      "rayon": 0,
      "couleur": "#ffe14a",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 3,
      "perteChaine": 0.7,
      "porteeChaine": 350
    },
    "fumigene": {
      "nom": "Grenade fumigène",
      "image": "",
      "type": "lob",
      "effet": "fumee",
      "vitesse": 9,
      "taille": 16,
      "rayon": 70,
      "couleur": "#9aa0a6",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350,
      "retard": 0,
      "poisonDuree": 0,
      "nuage": 5,
      "rayonNuage": 95,
      "degatsNuage": 250
    },
    "dard": {
      "nom": "Dard empoisonné",
      "image": "",
      "type": "droit",
      "effet": "poison",
      "vitesse": 14,
      "taille": 10,
      "rayon": 0,
      "couleur": "#7dff4a",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350,
      "retard": 0.5,
      "poisonDuree": 4,
      "nuage": 0,
      "rayonNuage": 90,
      "degatsNuage": 0
    },
    "rocher": {
      "nom": "Marteau de pierre",
      "image": "",
      "type": "lob",
      "effet": "impact",
      "vitesse": 7.5,
      "taille": 20,
      "rayon": 90,
      "couleur": "#a07850",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350,
      "retard": 0,
      "poisonDuree": 0,
      "nuage": 0,
      "rayonNuage": 90,
      "degatsNuage": 0,
      "onde": 150,
      "recul": 10,
      "forme": "onde"
    },
    "vent": {
      "nom": "Arc de vent",
      "image": "",
      "type": "droit",
      "effet": "etincelle",
      "vitesse": 15,
      "taille": 9,
      "rayon": 0,
      "couleur": "#bdf2ff",
      "rebonds": 2,
      "bonusRebond": 1.15,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350,
      "retard": 0,
      "poisonDuree": 0,
      "nuage": 0,
      "rayonNuage": 90,
      "degatsNuage": 0,
      "forme": "fleche"
    },
    "trident": {
      "nom": "Trident",
      "image": "",
      "type": "retour",
      "effet": "eclaboussure",
      "vitesse": 12,
      "taille": 16,
      "rayon": 0,
      "couleur": "#3aa6ff",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350,
      "retard": 0,
      "poisonDuree": 0,
      "nuage": 0,
      "rayonNuage": 90,
      "degatsNuage": 0,
      "recul": 16,
      "forme": "bulle"
    },
    "boulefeu": {
      "nom": "Boule de feu",
      "image": "",
      "type": "lob",
      "effet": "explosion",
      "vitesse": 10,
      "taille": 16,
      "rayon": 75,
      "couleur": "#ff6a00",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350,
      "retard": 0,
      "poisonDuree": 0,
      "nuage": 3,
      "rayonNuage": 70,
      "degatsNuage": 300,
      "forme": "feu"
    }
  },
  "maps": [
    {
      "nom": "Clairière",
      "herbe1": "#5cc24a",
      "herbe2": "#52b442",
      "mur": "#c98a4b",
      "murFace": "#8e5a2b",
      "buisson": "#2fae4a",
      "buissonFonce": "#1f7a35",
      "eau": "#3aa6e0",
      "grille": [
        "##############################",
        "#............BBBB............#",
        "#..BBB..................BBB..#",
        "#..B...C.##........##.....B..#",
        "#........##..WWWW..##........#",
        "#............WWWW............#",
        "#....###..............###....#",
        "#....#......BB..BB......#....#",
        "#.BB........BZZZZB........BB.#",
        "#.P.T..##...ZZCZZZ...##....E.#",
        "#......##...ZZZCZZ...##..T...#",
        "#.BB........BZZZZB........BB.#",
        "#....#......BB..BB......#....#",
        "#....###..............###....#",
        "#............WWWW............#",
        "#........##..WWWW..##........#",
        "#..B.....##........##.C...B..#",
        "#..BBB..................BBB..#",
        "#............BBBB............#",
        "##############################"
      ],
      "casseMurs": true,
      "casseBuissons": true,
      "pvBloc": 3000,
      "chanceObjet": 10,
      "chanceCoffre": 100
    },
    {
      "nom": "Plage des pirates",
      "herbe1": "#6fd35a",
      "herbe2": "#62c24f",
      "mur": "#c98a4b",
      "murFace": "#8e5a2b",
      "buisson": "#2fae4a",
      "buissonFonce": "#1f7a35",
      "eau": "#2fb8f0",
      "sable": "#f4d68e",
      "grille": [
        "##############################",
        "#WWWWS..................SSSSS#",
        "#WWWWS.BB...............SSSSS#",
        "#WWWSS.B..WWW.....BB....SSSSS#",
        "#WWWSS....WWW..E..C.....SSSSS#",
        "#SSSSS..................SSSSS#",
        "#SSSSS..##.....##...B...SSSSS#",
        "#SSPSS..#..........BB...SSSSS#",
        "#SSSSSB.....#ZZZZ.......SSSSS#",
        "#SSSSSB.....#ZZZZ.......STSSS#",
        "#SSSTS.......ZZZZ#.....BSSSSS#",
        "#SSSSS.......ZZZZ#.....BSSSSS#",
        "#SSSSS...BB..........#..SSPSS#",
        "#SSSSS...B...##.....##..SSSSS#",
        "#SSSSS..................SSSSS#",
        "#SSSSS.....C.....WWW....SSWWW#",
        "#SSSSS....BB.....WWW..B.SSWWW#",
        "#SSSSS...............BB.SWWWW#",
        "#SSSSS..................SWWWW#",
        "##############################"
      ],
      "casseMurs": true,
      "casseBuissons": true,
      "pvBloc": 3000,
      "chanceObjet": 10,
      "chanceCoffre": 100
    }
  ],
  "bosses": {
    "troll": {
      "nom": "TROLL",
      "image": "images/boss.png",
      "pvMax": 10000,
      "vitesse": 1.6,
      "degats": 3000,
      "delaiAttaque": 60,
      "rayonAttaque": 90,
      "taille": 48,
      "imageCarte": "",
      "arme": "",
      "porteeTir": 400,
      "degatsTir": 1500,
      "cadenceTir": 90
    }
  },
  "modes": [
    {
      "nom": "Chasse au boss",
      "description": "Bats le boss en solo",
      "type": "solo",
      "actif": true,
      "joueursMin": 1,
      "joueursMax": 1,
      "equipes": "chacun",
      "boss": true,
      "nbBoss": 1,
      "map": -1,
      "pointsVictoire": 20,
      "pointsDefaite": 2,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": false,
      "delaiReapparition": 3,
      "duree": 0,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Horde de trolls",
      "description": "Survis à plusieurs boss",
      "type": "solo",
      "actif": true,
      "joueursMin": 1,
      "joueursMax": 1,
      "equipes": "chacun",
      "boss": true,
      "nbBoss": 3,
      "map": -1,
      "pointsVictoire": 50,
      "pointsDefaite": 5,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": false,
      "delaiReapparition": 3,
      "duree": 0,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Duel 1V1",
      "description": "Affronte un joueur en ligne",
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 2,
      "equipes": "chacun",
      "boss": false,
      "nbBoss": 0,
      "map": -1,
      "pointsVictoire": 30,
      "pointsDefaite": 5,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 3,
      "duree": 150,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Équipes 2V2",
      "description": "Deux équipes s'affrontent",
      "type": "multi",
      "actif": true,
      "joueursMin": 4,
      "joueursMax": 4,
      "equipes": "deux",
      "boss": false,
      "nbBoss": 0,
      "map": -1,
      "pointsVictoire": 40,
      "pointsDefaite": 5,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 3,
      "duree": 150,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Coop contre les boss",
      "description": "Ensemble contre les boss",
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 4,
      "equipes": "coop",
      "boss": true,
      "nbBoss": 2,
      "map": -1,
      "pointsVictoire": 40,
      "pointsDefaite": 5,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": false,
      "delaiReapparition": 3,
      "duree": 0,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Zone de contrôle",
      "description": "Tiens la zone centrale",
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 4,
      "equipes": "deux",
      "boss": false,
      "nbBoss": 0,
      "typeBoss": "aleatoire",
      "map": -1,
      "pointsVictoire": 40,
      "pointsDefaite": 5,
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 3,
      "duree": 180,
      "objectif": "zone",
      "tempsZone": 40,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Guerre des cristaux",
      "description": "Détruis le cristal ennemi",
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 4,
      "equipes": "deux",
      "boss": false,
      "nbBoss": 0,
      "typeBoss": "aleatoire",
      "map": -1,
      "pointsVictoire": 40,
      "pointsDefaite": 5,
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 4,
      "duree": 240,
      "objectif": "bloc",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 4,
      "equipes": "deux",
      "boss": false,
      "nbBoss": 0,
      "map": -1,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 3,
      "nom": "Marathon",
      "description": "Cristaux puis zone : l'équipe qui gagne le plus d'étapes l'emporte",
      "pointsVictoire": 50,
      "pointsDefaite": 8,
      "duree": 0,
      "objectif": "marathon",
      "etapes": "bloc,zone",
      "tempsZone": 25,
      "pvCristal": 15000
    },
    {
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 4,
      "equipes": "deux",
      "boss": false,
      "nbBoss": 0,
      "map": -1,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 3,
      "nom": "Chasse au trésor",
      "description": "Trouve les trésors cachés avant l'équipe adverse",
      "pointsVictoire": 35,
      "pointsDefaite": 6,
      "duree": 150,
      "objectif": "tresor",
      "nbTresors": 14,
      "objectifTresors": 7
    }
  ],
  "pouvoirs": {
    "turbo": {
      "nom": "Turbo",
      "icone": "⚡",
      "couleur": "#ffe14a",
      "effet": "vitesse",
      "valeur": 1.6,
      "duree": 8,
      "rarete": 3
    },
    "force": {
      "nom": "Super force",
      "icone": "💪",
      "couleur": "#ff5a3c",
      "effet": "degats",
      "valeur": 2,
      "duree": 8,
      "rarete": 2
    },
    "bouclier": {
      "nom": "Bouclier",
      "icone": "🛡️",
      "couleur": "#5ad1ff",
      "effet": "bouclier",
      "valeur": 0.3,
      "duree": 6,
      "rarete": 2
    },
    "soin": {
      "nom": "Potion de soin",
      "icone": "❤️",
      "couleur": "#ff7aa8",
      "effet": "soin",
      "valeur": 0.4,
      "duree": 0,
      "rarete": 3
    },
    "rafale": {
      "nom": "Munitions infinies",
      "icone": "♾️",
      "couleur": "#b67aff",
      "effet": "munitions",
      "valeur": 1,
      "duree": 6,
      "rarete": 1
    },
    "fantome": {
      "nom": "Fantôme",
      "icone": "👻",
      "couleur": "#dddddd",
      "effet": "invisible",
      "valeur": 1,
      "duree": 6,
      "rarete": 1
    }
  },
  "version": 12,
  "app": {
    "nom": "Bastory",
    "nomCourt": "Bastory",
    "icone": "images/icone-maskable-512.png",
    "couleur": "#2b1d6b"
  },
  "elements": {
    "terre": {
      "nom": "Terre",
      "icone": "🌍",
      "couleur": "#b7791f",
      "capacite": "brise",
      "valeur": 60,
      "gainVictoire": 30,
      "gainDefaite": 10,
      "superNom": "Séisme titan",
      "superCharge": 7000,
      "actionNom": "Charge",
      "actionRecharge": 7
    },
    "air": {
      "nom": "Air",
      "icone": "💨",
      "couleur": "#38bdf8",
      "capacite": "saut",
      "altitude": 24,
      "valeur": 0,
      "gainVictoire": 30,
      "gainDefaite": 10,
      "superNom": "Tempête de flèches",
      "superCharge": 5000,
      "actionNom": "Saut",
      "actionRecharge": 5
    },
    "eau": {
      "nom": "Eau",
      "icone": "💧",
      "couleur": "#2563eb",
      "capacite": "nage",
      "valeur": 1.35,
      "soin": 1.5,
      "gainVictoire": 30,
      "gainDefaite": 10,
      "superNom": "Raz-de-marée",
      "superCharge": 6000,
      "actionNom": "Bulle",
      "actionRecharge": 8
    },
    "feu": {
      "nom": "Feu",
      "icone": "🔥",
      "couleur": "#ef4444",
      "capacite": "feu",
      "valeur": 120,
      "duree": 2,
      "gainVictoire": 30,
      "gainDefaite": 10,
      "superNom": "Souffle du dragon",
      "superCharge": 6500,
      "actionNom": "Brasier",
      "actionRecharge": 8
    }
  },
  "progression": {
    "niveauMax": 10,
    "coutBase": 50,
    "coutMult": 1.5,
    "bonusPV": 8,
    "bonusDegats": 6,
    "bonusVitesse": 2
  },
  "recompenses": [
    {
      "victoires": 1,
      "element": "terre",
      "quantite": 20
    },
    {
      "victoires": 3,
      "element": "air",
      "quantite": 30
    },
    {
      "victoires": 5,
      "element": "eau",
      "quantite": 40
    },
    {
      "victoires": 8,
      "element": "feu",
      "quantite": 50
    },
    {
      "victoires": 12,
      "element": "tous",
      "quantite": 30
    },
    {
      "victoires": 20,
      "element": "terre",
      "quantite": 100
    },
    {
      "victoires": 30,
      "element": "air",
      "quantite": 120
    },
    {
      "victoires": 45,
      "element": "eau",
      "quantite": 150
    },
    {
      "victoires": 60,
      "element": "feu",
      "quantite": 180
    },
    {
      "victoires": 100,
      "element": "tous",
      "quantite": 150
    }
  ]
};

// Met à niveau une config existante (ajoute les nouveaux réglages, retire les anciens)
function migrerConfig(c) {
  const D = CONFIG_PAR_DEFAUT, copie = o => JSON.parse(JSON.stringify(o)), def = (o, d) => { for (const k in d) if (o[k] === undefined) o[k] = d[k]; return o; };
  if (!c.bosses) c.bosses = { troll: c.boss || copie(D.bosses.troll) }; delete c.boss;
  ['modes', 'pouvoirs', 'app', 'elements', 'progression', 'recompenses'].forEach(k => { if (!c[k] || (Array.isArray(c[k]) && !c[k].length)) c[k] = copie(D[k]); });
  for (const k in D.armes) if (!c.armes[k] && ['seisme', 'ricochet', 'eclair', 'fumigene', 'dard', 'rocher', 'vent', 'trident', 'boulefeu'].includes(k)) c.armes[k] = copie(D.armes[k]);
  if ((c.version || 0) < 8) { // v8 : persos = vrais modèles 3D .glb + éléments ; les anciens persos "assemblés" sont retirés
    c.persos = c.persos.filter(p => p.image || p.modele);
    c.persos.forEach(p => Object.keys(p).forEach(k => { if (k.startsWith('t3') || k === 'mode3D') delete p[k]; }));
    D.persos.filter(p => p.modele).forEach(p => { if (!c.persos.some(x => x.nom === p.nom)) c.persos.unshift(copie(p)); });
    ['v3d', 'v3d2', 'v3d3'].forEach(k => delete c[k]); c.version = 8;
  }
  if ((c.version || 0) < 9) { // v9 : gameplay plus posé, armes typées, super/action, sable, marathon, chasse au trésor, récompenses
    const P = {"ROKH":{"vitesse":3,"pvMax":8500,"degats":2000,"portee":300,"delaiTir":55},"ZEPHYR":{"vitesse":4.6,"pvMax":3800,"degats":950,"portee":520,"delaiTir":20,"modeleEchelle":1.2},"NAIA":{"vitesse":4,"pvMax":5400,"degats":1250,"portee":400,"delaiTir":28},"PYRO":{"vitesse":4.1,"pvMax":5000,"degats":1600,"portee":360,"delaiTir":34},"WIXY":{"vitesse":3.4},"BORA":{"vitesse":4.3}};
    c.persos.forEach(p => { if (P[p.nom]) Object.assign(p, P[p.nom]); else p.vitesse = +((+p.vitesse || 4) * 0.82).toFixed(2); });
    ['rocher', 'vent', 'trident', 'boulefeu'].forEach(k => { if (c.armes[k]) ['vitesse', 'onde', 'recul', 'forme', 'rebonds', 'effet', 'nuage', 'degatsNuage'].forEach(x => { if (D.armes[k][x] !== undefined) c.armes[k][x] = D.armes[k][x]; }); });
    for (const k in D.elements) if (c.elements[k]) def(c.elements[k], D.elements[k]);
    D.modes.filter(m => ['marathon', 'tresor'].includes(m.objectif)).forEach(m => { if (!c.modes.some(x => x.nom === m.nom)) c.modes.push(copie(m)); });
    D.maps.filter(m => m.sable).forEach(m => { if (!c.maps.some(x => x.nom === m.nom)) c.maps.push(copie(m)); });
    c.version = 9;
  }
  if ((c.version || 0) < 10) { // v10 : persos plus lents, Zéphyr marche et saute au lieu de voler
    c.persos.forEach(p => p.vitesse = +((+p.vitesse || 4) * 0.85).toFixed(2));
    if (c.elements.air) { if (c.elements.air.capacite === 'vol') c.elements.air.capacite = 'saut'; if (c.elements.air.actionNom === 'Rafale') c.elements.air.actionNom = 'Saut'; }
    c.version = 10;
  }
  if ((c.version || 0) < 11) { // v11 : Rokh frappe au marteau (onde de choc au sol, courte portée)
    if (c.armes.rocher) Object.assign(c.armes.rocher, { forme: 'onde', vitesse: 11, taille: 22, rayon: 95, onde: 150, effet: 'impact' });
    c.persos.forEach(p => { if (p.nom === 'ROKH') p.portee = 240; });
    c.version = 11;
  }
  if ((c.version || 0) < 12) { if (c.armes.rocher) c.armes.rocher.vitesse = 26; c.version = 12; } // v12 : le marteau frappe le sol tout de suite
  if (/wixy\.png$/i.test((c.app || {}).icone || '')) c.app.icone = 'images/icone-maskable-512.png'; // nouvelle icône PWA
  c.modes.forEach(m => {
    if (m.type === '1v1') { m.type = 'multi'; m.joueursMin = m.joueursMin || 2; m.joueursMax = m.joueursMax || 2; }
    def(m, { joueursMin: 1, joueursMax: 1, equipes: 'chacun', pointsVictoire: 30, pointsDefaite: 5, bots: true, attenteBots: 15, reapparition: false, delaiReapparition: 3, duree: 0,
             objectif: 'standard', etapes: 'bloc,zone', nbTresors: 14, objectifTresors: 7, tempsZone: 30, pvCristal: 20000, degatsCristal: 800, porteeCristal: 350, cadenceCristal: 60, botsObjets: true, niveauBoss: 1, niveauBots: 1, botsAdaptatifs: true });
  });
  c.persos.forEach(p => def(p, { imageCarte: '', munitions: 3, recharge: 60, element: '', modele: '', modeleEchelle: 1, modeleRotation: 0, animRepos: '', animMarche: '', animAttaque: '', animTouche: '', animMort: '', animReleve: '' }));
  Object.values(c.bosses).forEach(b => def(b, { imageCarte: '', arme: '', porteeTir: 400, degatsTir: 1500, cadenceTir: 90, modele: '', modeleEchelle: 1, modeleRotation: 0, animRepos: '', animMarche: '', animAttaque: '', animTouche: '', animMort: '' }));
  Object.values(c.armes).forEach(a => def(a, { rebonds: 0, bonusRebond: 1.2, chaine: 0, perteChaine: 0.7, porteeChaine: 350, onde: 0, recul: 0, forme: '', retard: 0, poisonDuree: 0, nuage: 0, rayonNuage: 90, degatsNuage: 150 }));
  c.maps.forEach(m => def(m, { casseMurs: true, casseBuissons: true, pvBloc: 3000, chanceObjet: 10, chanceCoffre: 100, sable: '#f4d68e' }));
  return c;
}
