// ⚙️ DONNÉES DU JEU — config de secours (la version en ligne est dans Firebase, éditable via admin.html)
const CONFIG_PAR_DEFAUT = {
  "persos": [
    {
      "nom": "WIXY",
      "image": "images/wixy.png",
      "couleur": "#3498db",
      "pvMax": 6000,
      "vitesse": 4,
      "arme": "bombe",
      "degats": 2000,
      "portee": 300,
      "delaiTir": 45,
      "imageCarte": "",
      "munitions": 3,
      "recharge": 60,
      "mode3D": true,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": "",
      "t3Espece": "lapin",
      "t3CouleursImage": true,
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "cape",
      "t3Tenue2": "couronne",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#7c3aed"
    },
    {
      "nom": "BORA",
      "image": "images/bora.png",
      "couleur": "#9b59b6",
      "pvMax": 4800,
      "vitesse": 5.5,
      "arme": "boomerang",
      "degats": 1250,
      "portee": 450,
      "delaiTir": 22,
      "imageCarte": "",
      "munitions": 3,
      "recharge": 45,
      "mode3D": true,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": "",
      "t3Espece": "dragon",
      "t3CouleursImage": true,
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "ceinture",
      "t3Tenue2": "aucune",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": ""
    },
    {
      "nom": "MINOU",
      "image": "",
      "imageCarte": "",
      "couleur": "#f4a261",
      "pvMax": 4600,
      "vitesse": 5.5,
      "arme": "boomerang",
      "degats": 1300,
      "portee": 420,
      "delaiTir": 22,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "chat",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "echarpe",
      "t3Tenue2": "lunettes",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#e63946",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "BRUNO",
      "image": "",
      "imageCarte": "",
      "couleur": "#8b5a2b",
      "pvMax": 7800,
      "vitesse": 3.6,
      "arme": "bombe",
      "degats": 2200,
      "portee": 300,
      "delaiTir": 50,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "ours",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "casque",
      "t3Tenue2": "armure",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#5a6b7d",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "FOXY",
      "image": "",
      "imageCarte": "",
      "couleur": "#ef7a2a",
      "pvMax": 4800,
      "vitesse": 5.8,
      "arme": "ricochet",
      "degats": 1200,
      "portee": 480,
      "delaiTir": 20,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "renard",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "cape",
      "t3Tenue2": "ceinture",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#1d4ed8",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "PINGO",
      "image": "",
      "imageCarte": "",
      "couleur": "#1f2a44",
      "pvMax": 5200,
      "vitesse": 4.6,
      "arme": "fumigene",
      "degats": 900,
      "portee": 380,
      "delaiTir": 40,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "pingouin",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "casquette",
      "t3Tenue2": "echarpe",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#ef4444",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "TIGRA",
      "image": "",
      "imageCarte": "",
      "couleur": "#f39c12",
      "pvMax": 5600,
      "vitesse": 5.2,
      "arme": "eclair",
      "degats": 1400,
      "portee": 400,
      "delaiTir": 26,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "tigre",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "ceinture",
      "t3Tenue2": "aucune",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#111827",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "PANDI",
      "image": "",
      "imageCarte": "",
      "couleur": "#9ca3af",
      "pvMax": 6200,
      "vitesse": 4.2,
      "arme": "dard",
      "degats": 1100,
      "portee": 440,
      "delaiTir": 28,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "panda",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "sac",
      "t3Tenue2": "chapeau",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#16a34a",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "CROA",
      "image": "",
      "imageCarte": "",
      "couleur": "#6ab04c",
      "pvMax": 4400,
      "vitesse": 6.0,
      "arme": "tir",
      "degats": 1000,
      "portee": 460,
      "delaiTir": 18,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "grenouille",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "couronne",
      "t3Tenue2": "aucune",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#ffd54a",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "HOOT",
      "image": "",
      "imageCarte": "",
      "couleur": "#8d6e63",
      "pvMax": 5000,
      "vitesse": 4.6,
      "arme": "seisme",
      "degats": 1500,
      "portee": 360,
      "delaiTir": 45,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "hibou",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "lunettes",
      "t3Tenue2": "cape",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#6d28d9",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "LUNA",
      "image": "",
      "imageCarte": "",
      "couleur": "#d8b4fe",
      "pvMax": 5000,
      "vitesse": 5.4,
      "arme": "eclair",
      "degats": 1300,
      "portee": 420,
      "delaiTir": 24,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "licorne",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "noeud",
      "t3Tenue2": "aucune",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#ec4899",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    },
    {
      "nom": "DRACO",
      "image": "",
      "imageCarte": "",
      "couleur": "#27ae60",
      "pvMax": 6800,
      "vitesse": 4.4,
      "arme": "bombe",
      "degats": 2100,
      "portee": 320,
      "delaiTir": 46,
      "munitions": 3,
      "recharge": 55,
      "mode3D": true,
      "t3Espece": "dragon",
      "t3CouleursImage": false,
      "t3Skin": "",
      "t3Taille": 1,
      "t3Tete": 1,
      "t3CorpsL": 1,
      "t3CorpsH": 1,
      "t3BrasL": 1,
      "t3BrasE": 1,
      "t3JambesL": 1,
      "t3JambesE": 1,
      "t3Oreilles": "auto",
      "t3Queue": "auto",
      "t3Museau": "auto",
      "t3Yeux": "auto",
      "t3Motif": "auto",
      "t3Tenue1": "armure",
      "t3Tenue2": "couronne",
      "t3Tenue3": "aucune",
      "t3CouleurTenue": "#b91c1c",
      "t3Couleur1": "",
      "t3Couleur2": "",
      "t3Couleur3": ""
    }
  ],
  "armes": {
    "bombe": {
      "nom": "Bombe",
      "image": "images/bombe.png",
      "type": "lob",
      "effet": "explosion",
      "vitesse": 9,
      "taille": 18,
      "rayon": 80,
      "couleur": "#ff9f1a",
      "forme": "zone",
      "nbCases": 3,
      "typeCase": "#",
      "dureeCase": 5,
      "delaiCase": 4
    },
    "boomerang": {
      "nom": "Boomerang",
      "image": "images/boomerang.png",
      "type": "retour",
      "effet": "entaille",
      "vitesse": 11,
      "taille": 18,
      "rayon": 0,
      "couleur": "#9cff57",
      "forme": "zone",
      "nbCases": 3,
      "typeCase": "#",
      "dureeCase": 5,
      "delaiCase": 4
    },
    "tir": {
      "nom": "Tir magique",
      "image": "",
      "type": "droit",
      "effet": "etincelle",
      "vitesse": 13,
      "taille": 10,
      "rayon": 0,
      "couleur": "#ffe14a",
      "forme": "zone",
      "nbCases": 3,
      "typeCase": "#",
      "dureeCase": 5,
      "delaiCase": 4
    },
    "seisme": {
      "nom": "Séisme",
      "image": "",
      "type": "terrain",
      "effet": "impact",
      "vitesse": 10,
      "taille": 16,
      "rayon": 0,
      "couleur": "#c98a4b",
      "forme": "mur",
      "nbCases": 3,
      "typeCase": "#",
      "dureeCase": 5,
      "delaiCase": 4
    },
    "ricochet": {
      "nom": "Laser ricochet",
      "image": "",
      "type": "droit",
      "effet": "etincelle",
      "vitesse": 14,
      "taille": 10,
      "rayon": 0,
      "couleur": "#5ad1ff",
      "rebonds": 3,
      "bonusRebond": 1.25,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350
    },
    "eclair": {
      "nom": "Éclair chercheur",
      "image": "",
      "type": "droit",
      "effet": "foudre",
      "vitesse": 13,
      "taille": 10,
      "rayon": 0,
      "couleur": "#ffe14a",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 3,
      "perteChaine": 0.7,
      "porteeChaine": 350
    },
    "fumigene": {
      "nom": "Grenade fumigène",
      "image": "",
      "type": "lob",
      "effet": "fumee",
      "vitesse": 9,
      "taille": 16,
      "rayon": 70,
      "couleur": "#9aa0a6",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350,
      "retard": 0,
      "poisonDuree": 0,
      "nuage": 5,
      "rayonNuage": 95,
      "degatsNuage": 250
    },
    "dard": {
      "nom": "Dard empoisonné",
      "image": "",
      "type": "droit",
      "effet": "poison",
      "vitesse": 14,
      "taille": 10,
      "rayon": 0,
      "couleur": "#7dff4a",
      "rebonds": 0,
      "bonusRebond": 1.2,
      "chaine": 0,
      "perteChaine": 0.7,
      "porteeChaine": 350,
      "retard": 0.5,
      "poisonDuree": 4,
      "nuage": 0,
      "rayonNuage": 90,
      "degatsNuage": 0
    }
  },
  "maps": [
    {
      "nom": "Clairière",
      "herbe1": "#5cc24a",
      "herbe2": "#52b442",
      "mur": "#c98a4b",
      "murFace": "#8e5a2b",
      "buisson": "#2fae4a",
      "buissonFonce": "#1f7a35",
      "eau": "#3aa6e0",
      "grille": [
        "##############################",
        "#............BBBB............#",
        "#..BBB..................BBB..#",
        "#..B...C.##........##.....B..#",
        "#........##..WWWW..##........#",
        "#............WWWW............#",
        "#....###..............###....#",
        "#....#......BB..BB......#....#",
        "#.BB........BZZZZB........BB.#",
        "#.P.T..##...ZZCZZZ...##....E.#",
        "#......##...ZZZCZZ...##..T...#",
        "#.BB........BZZZZB........BB.#",
        "#....#......BB..BB......#....#",
        "#....###..............###....#",
        "#............WWWW............#",
        "#........##..WWWW..##........#",
        "#..B.....##........##.C...B..#",
        "#..BBB..................BBB..#",
        "#............BBBB............#",
        "##############################"
      ],
      "casseMurs": true,
      "casseBuissons": true,
      "pvBloc": 3000,
      "chanceObjet": 10,
      "chanceCoffre": 100
    }
  ],
  "bosses": {
    "troll": {
      "nom": "TROLL",
      "image": "images/boss.png",
      "pvMax": 10000,
      "vitesse": 1.6,
      "degats": 3000,
      "delaiAttaque": 60,
      "rayonAttaque": 90,
      "taille": 48,
      "imageCarte": "",
      "arme": "",
      "porteeTir": 400,
      "degatsTir": 1500,
      "cadenceTir": 90
    }
  },
  "modes": [
    {
      "nom": "Chasse au boss",
      "description": "Bats le boss en solo",
      "type": "solo",
      "actif": true,
      "joueursMin": 1,
      "joueursMax": 1,
      "equipes": "chacun",
      "boss": true,
      "nbBoss": 1,
      "map": -1,
      "pointsVictoire": 20,
      "pointsDefaite": 2,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": false,
      "delaiReapparition": 3,
      "duree": 0,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Horde de trolls",
      "description": "Survis à plusieurs boss",
      "type": "solo",
      "actif": true,
      "joueursMin": 1,
      "joueursMax": 1,
      "equipes": "chacun",
      "boss": true,
      "nbBoss": 3,
      "map": -1,
      "pointsVictoire": 50,
      "pointsDefaite": 5,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": false,
      "delaiReapparition": 3,
      "duree": 0,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Duel 1V1",
      "description": "Affronte un joueur en ligne",
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 2,
      "equipes": "chacun",
      "boss": false,
      "nbBoss": 0,
      "map": -1,
      "pointsVictoire": 30,
      "pointsDefaite": 5,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 3,
      "duree": 150,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Équipes 2V2",
      "description": "Deux équipes s'affrontent",
      "type": "multi",
      "actif": true,
      "joueursMin": 4,
      "joueursMax": 4,
      "equipes": "deux",
      "boss": false,
      "nbBoss": 0,
      "map": -1,
      "pointsVictoire": 40,
      "pointsDefaite": 5,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 3,
      "duree": 150,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Coop contre les boss",
      "description": "Ensemble contre les boss",
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 4,
      "equipes": "coop",
      "boss": true,
      "nbBoss": 2,
      "map": -1,
      "pointsVictoire": 40,
      "pointsDefaite": 5,
      "typesBoss": [],
      "bots": true,
      "attenteBots": 15,
      "reapparition": false,
      "delaiReapparition": 3,
      "duree": 0,
      "objectif": "standard",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Zone de contrôle",
      "description": "Tiens la zone centrale",
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 4,
      "equipes": "deux",
      "boss": false,
      "nbBoss": 0,
      "typeBoss": "aleatoire",
      "map": -1,
      "pointsVictoire": 40,
      "pointsDefaite": 5,
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 3,
      "duree": 180,
      "objectif": "zone",
      "tempsZone": 40,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    },
    {
      "nom": "Guerre des cristaux",
      "description": "Détruis le cristal ennemi",
      "type": "multi",
      "actif": true,
      "joueursMin": 2,
      "joueursMax": 4,
      "equipes": "deux",
      "boss": false,
      "nbBoss": 0,
      "typeBoss": "aleatoire",
      "map": -1,
      "pointsVictoire": 40,
      "pointsDefaite": 5,
      "bots": true,
      "attenteBots": 15,
      "reapparition": true,
      "delaiReapparition": 4,
      "duree": 240,
      "objectif": "bloc",
      "tempsZone": 30,
      "pvCristal": 20000,
      "degatsCristal": 800,
      "porteeCristal": 350,
      "cadenceCristal": 60,
      "botsObjets": true,
      "niveauBoss": 1,
      "niveauBots": 1,
      "botsAdaptatifs": true
    }
  ],
  "pouvoirs": {
    "turbo": {
      "nom": "Turbo",
      "icone": "⚡",
      "couleur": "#ffe14a",
      "effet": "vitesse",
      "valeur": 1.6,
      "duree": 8,
      "rarete": 3
    },
    "force": {
      "nom": "Super force",
      "icone": "💪",
      "couleur": "#ff5a3c",
      "effet": "degats",
      "valeur": 2,
      "duree": 8,
      "rarete": 2
    },
    "bouclier": {
      "nom": "Bouclier",
      "icone": "🛡️",
      "couleur": "#5ad1ff",
      "effet": "bouclier",
      "valeur": 0.3,
      "duree": 6,
      "rarete": 2
    },
    "soin": {
      "nom": "Potion de soin",
      "icone": "❤️",
      "couleur": "#ff7aa8",
      "effet": "soin",
      "valeur": 0.4,
      "duree": 0,
      "rarete": 3
    },
    "rafale": {
      "nom": "Munitions infinies",
      "icone": "♾️",
      "couleur": "#b67aff",
      "effet": "munitions",
      "valeur": 1,
      "duree": 6,
      "rarete": 1
    },
    "fantome": {
      "nom": "Fantôme",
      "icone": "👻",
      "couleur": "#dddddd",
      "effet": "invisible",
      "valeur": 1,
      "duree": 6,
      "rarete": 1
    }
  },
  "version": 7,
  "app": {
    "nom": "Bastory",
    "nomCourt": "Bastory",
    "icone": "images/wixy.png",
    "couleur": "#2b1d6b"
  }
};

// Met à niveau une ancienne config (ajoute les nouveaux paramètres avec des valeurs par défaut)
function migrerConfig(c) {
  const D = CONFIG_PAR_DEFAUT, copie = o => JSON.parse(JSON.stringify(o));
  const def = (o, d) => { for (const k in d) if (o[k] === undefined) o[k] = d[k]; return o; };
  if (!c.bosses) c.bosses = { troll: c.boss || copie(D.bosses.troll) };
  delete c.boss;
  if (!c.modes || !c.modes.length) c.modes = copie(D.modes);
  if (!c.pouvoirs) c.pouvoirs = copie(D.pouvoirs);
  c.modes.forEach(m => {
    if (m.type === '1v1') { m.type = 'multi'; m.joueursMin = m.joueursMin || 2; m.joueursMax = m.joueursMax || 2; }
    def(m, { joueursMin: 1, joueursMax: 1, equipes: 'chacun', pointsVictoire: 30, pointsDefaite: 5 });
  });
  if ((c.version || 0) < 3) { if (!c.armes.seisme) c.armes.seisme = copie(D.armes.seisme); c.version = 3; }
  if (c.version < 4) { ['ricochet', 'eclair'].forEach(k => { if (!c.armes[k]) c.armes[k] = copie(D.armes[k]); }); c.version = 4; }
  if (c.version < 5) { ['fumigene', 'dard'].forEach(k => { if (!c.armes[k]) c.armes[k] = copie(D.armes[k]); }); c.version = 5; }
  c.modes.forEach(m => def(m, { reapparition: false, delaiReapparition: 3, duree: 0 }));
  c.modes.forEach(m => def(m, { objectif: 'standard', tempsZone: 30, pvCristal: 20000, degatsCristal: 800, porteeCristal: 350, cadenceCristal: 60, botsObjets: true }));
  c.modes.forEach(m => def(m, { niveauBoss: 1, niveauBots: 1, botsAdaptatifs: true }));
  if (!c.app) c.app = copie(D.app);
  if (!c.v3d2) { // 3D v2 : espèces animales + habillages, et une ménagerie d'exemples
    c.persos.forEach(p => { p.mode3D = true; ['t3Oreilles', 't3Queue'].forEach(k => p[k] = 'auto'); if (!p.t3Espece) { p.t3Espece = 'lapin'; p.t3CouleursImage = true; } });
    D.persos.filter(p => !p.image).forEach(p => { if (!c.persos.some(x => x.nom === p.nom)) c.persos.push(copie(p)); });
    c.v3d2 = true;
  }
  c.persos.forEach(p => def(p, { t3Espece: 'chat', t3CouleursImage: false, t3Museau: 'auto', t3Yeux: 'auto', t3Motif: 'auto', t3Tenue1: 'aucune', t3Tenue2: 'aucune', t3Tenue3: 'aucune', t3CouleurTenue: '' }));
  if (!c.v3d) { c.persos.forEach(p => { if (p.mode3D === undefined) p.mode3D = true; }); c.v3d = true; } // lot 3 : persos 3D activés
  c.persos.forEach(p => def(p, { mode3D: false, t3Skin: '', t3Taille: 1, t3Tete: 1, t3CorpsL: 1, t3CorpsH: 1, t3BrasL: 1, t3BrasE: 1, t3JambesL: 1, t3JambesE: 1, t3Oreilles: 'aucune', t3Queue: false, t3Couleur1: '', t3Couleur2: '', t3Couleur3: '' }));
  if (c.version < 6) { D.modes.slice(-2).forEach(m => { if (!c.modes.some(x => x.nom === m.nom)) c.modes.push(copie(m)); }); c.version = 6; }
  Object.values(c.armes).forEach(a => def(a, { retard: 0, poisonDuree: 0, nuage: 0, rayonNuage: 90, degatsNuage: 150 }));
  c.modes.forEach(m => def(m, { bots: true, attenteBots: 15 }));
  Object.values(c.armes).forEach(a => def(a, { rebonds: 0, bonusRebond: 1.2, chaine: 0, perteChaine: 0.7, porteeChaine: 350 }));
  Object.values(c.bosses).forEach(b => def(b, { arme: '', porteeTir: 400, degatsTir: 1500, cadenceTir: 90 }));
  c.modes.forEach(m => { if (!Array.isArray(m.typesBoss)) m.typesBoss = m.typeBoss && m.typeBoss !== 'aleatoire' ? [m.typeBoss] : []; delete m.typeBoss; });
  Object.values(c.armes).forEach(a => def(a, { forme: 'zone', nbCases: 3, typeCase: '#', dureeCase: 5, delaiCase: 4 }));
  c.persos.forEach(p => def(p, { imageCarte: '', munitions: 3, recharge: 60 }));
  Object.values(c.bosses).forEach(b => def(b, { imageCarte: '' }));
  c.maps.forEach(m => def(m, { casseMurs: true, casseBuissons: true, pvBloc: 3000, chanceObjet: 10, chanceCoffre: 100 }));
  return c;
}
